name: On merge

on:
  push:
    branches:
      - master

jobs:
  release-publish:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # NPM_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile

      - name: Run Build
        shell: bash
        run: yarn build

      # Setting up the SSH agent to be able to commit back to the repository
      # https://github.com/webfactory/ssh-agent
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}

      # - name: Authenticate with registry
      #   shell: bash
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMJS_PUBLISH_TOKEN }}" ~/.npmrc

      - name: Release and publish
        shell: bash
        run: |
          git fetch --tags
          yarn auto-changelog
          yarn auto-version
          # npm publish --access public
          git push --follow-tags --set-upstream origin master
          # yarn auto-release-only

      - name: Merge changes back into develop branch
        shell: bash
        run: |
          git checkout develop
          git merge master --ff-only
          git push -u origin develop
